// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isjjyfwwuuxitiquucjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzamp5Znd3dXV4aXRpcXV1Y2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzU1OTMsImV4cCI6MjA2NDYxMTU5M30.k2roMp1mr2Oc7QrqB36fbeW92GDTeSYBOimjcWOAhKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);